### ISSUE TITLE
cljr-rename-symbol local variable inside an assert

### ISSUE THREAD

**Issue by aiba** [clojure-emacs/clj-refactor.el#344] opened 2016-09-12 06:42 UTC
Seems like if you rename a local symbol inside a function, references inside an assert will not get renamed.

## Steps to reproduce the problem

```clj
(defn f [x]
  (assert (not (nil? x)))
  (+ x 1))
```

Put cursor over first occurrence of x.  cljr-rename-symbol x->y.

## Expected behavior

```clj
(defn f [y]
  (assert (not (nil? y)))
  (+ y 1))
```

## Actual behavior

```clj
(defn f [y]
  (assert (not (nil? x)))   ;; <-- didn't get renamed
  (+ y 1))
```

## Environment & Version information

```
clj-refactor 2.3.0-SNAPSHOT (package: 20160621.902), refactor-nrepl 2.3.0-SNAPSHOT
CIDER 0.14.0snapshot (package: 20160830.23)
Clojure 1.8.0
Leiningen 2.6.1 on Java 1.8.0_92 Java HotSpot(TM) 64-Bit Server VM
GNU Emacs 25.1.1 (x86_64-apple-darwin15.6.0, Carbon Version 157 AppKit 1404.47) of 2016-08-30
OS X 10.11.6
```

**Comment by benedekfazekas** [comment] 2016-09-18 11:53
I am having trouble reproducing this problem. Testing with the same versions (cider package is 5 days older but I assume that should not make a difference; cljr package is the same). Local symbols in an assert including copy-pasting your example works for me.

The only difference in my environment is my emacs is still 24.5. Any chance you can retest with emacs 24 (I will try to find time to test with emacs 25 but it may not happen this week).

**Comment by expez** [comment] 2016-09-18 12:24
Think this might be affected by whether asserts are enabled or not?

**Comment by benedekfazekas** [comment] 2016-09-18 12:55
good shout @expez. if `*assert*` is false then the occurrence is missed. Guessing nothing in the AST for it as the macro returns nothing this case.

**Comment by expez** [comment] 2016-09-18 13:08
Yeah, I'm inclined to just close this.  Is there any reason to turn off asserts at dev time?  Thoughts?

**Comment by benedekfazekas** [comment] 2016-09-18 13:11
let's hear what @aiba says, surely he has a reason. also would be nicer if this just worked no matter what `*assert*` is set to.

**Comment by aiba** [comment] 2016-09-18 15:13
I actually have `*assert*` true, and it's still missed on my setup.  I will retest with emacs 24.

**Comment by aiba** [comment] 2016-09-18 16:02
I tracked this down to the fact that I have `("assert" . 10003)` in `prettify-symbols-alist` and `prettify-symbols-mode` was active.

So I suppose this is an incompatibility between cljr and prettify-symbols-mode, not about macros or emacs version.

**Comment by benedekfazekas** [comment] 2016-09-18 16:13
indeed. as prettify symbol messes up your column count. can confuse your indentation too. @Malabarba has a good post with workarounds on his blog in case you have not read it.

I am also in favor of closing this at this point.

**Closed** 2016-09-18 16:14 UTC
Labels: bug
