### ISSUE TITLE
load clj-refactor.el error

### ISSUE THREAD

**Issue by stardiviner** [clojure-emacs/clj-refactor.el#374] opened 2017-05-01 01:31 UTC
I got error when `(require 'clj-refactor)`:
#+BEGIN_EXAMPLE
 Error loading autoloads: (wrong-type-argument stringp package-desc)
#+END_EXAMPLE

Then I set edebug on some functions like the following:

``` elisp
(epl-package-from-lisp-file "/home/stardiviner/.emacs.d/elpa/clj-refactor-20170430.1144/clj-refactor.el")

(with-temp-buffer
  (insert-file-contents "/home/stardiviner/.emacs.d/elpa/clj-refactor-20170430.1144/clj-refactor.el")
  (condition-case err
      (epl-package-from-buffer (current-buffer))
    ;; ;; Attach file names to invalid package errors
    ;; (epl-invalid-package
    ;;  (signal 'epl-invalid-package-file (cons file-name (cdr err))))
    ;; ;; Forward other errors
    ;; (error (signal (car err) (cdr err)))
    ))
```

```elisp
{ epl-package-from-lisp-file args: (/home/stardiviner/.emacs.d/elpa/clj-refactor-20170430.1144/clj-refactor.el)
{ epl-package--parse-info args: (#s(package-desc clj-refactor (2 3 0 -4) A collection of clojure refactoring functions ((emacs (24 4)) (s (1 8 0)) (seq (2 19)) (yasnippet (0 6 1)) (paredit (24)) (multiple-cursors (1 2 2)) (clojure-mode (5 6 1)) (cider (0 11 0)) (edn (1 1 2)) (inflections (2 3)) (hydra (0 13 2))) single nil nil ((:authors (Magnar Sveen . magnars@gmail.com) (Lars Andersen . expez@expez.com) (Benedek Fazekas . benedek.fazekas@gmail.com)) (:maintainer Magnar Sveen . magnars@gmail.com)) nil))
```

```
Debugger entered--Lisp error: (wrong-type-argument stringp package-desc)
  signal(wrong-type-argument (stringp package-desc))
  epl-package-from-lisp-file("/home/stardiviner/.emacs.d/elpa/clj-refactor-20170430.1144/clj-refactor.el")
  epl-package-from-file("/home/stardiviner/.emacs.d/elpa/clj-refactor-20170430.1144/clj-refactor.el")
  (epl-package-version (epl-package-from-file source))
  (let* ((source (pkg-info-library-source library)) (version (epl-package-version (epl-package-from-file source)))) (pkg-info--show-version-and-return version show))
  pkg-info-library-version(clj-refactor)
  (or orig-version (pkg-info-library-version library))
  (let* ((package (or package (if (stringp library) (intern library) library))) (orig-version (condition-case nil (pkg-info-library-original-version library) (error nil))) (lib-version (or orig-version (pkg-info-library-version library))) (pkg-version (condition-case nil (pkg-info-package-version package) (error nil))) (version (if (and pkg-version (not (version-list-= lib-version pkg-version))) (format "%s (package: %s)" (pkg-info-format-version lib-version) (pkg-info-format-version pkg-version)) (pkg-info-format-version lib-version)))) (pkg-info--show-version-and-return version show))
  pkg-info-version-info(clj-refactor)
  cljr--version(t)
  cljr--inject-jack-in-dependencies()
  #[0 "\300 \207" [cljr--inject-jack-in-dependencies] 1]()
  eval-after-load(cider #[0 "\300 \207" [cljr--inject-jack-in-dependencies] 1])

  #<subr require>(clj-refactor nil t)
  ad-Advice-require(#<subr require> clj-refactor nil t)
  apply(ad-Advice-require #<subr require> (clj-refactor nil t))
  require(clj-refactor nil t)
  (not (require 'clj-refactor nil 't))
  (if (not (require 'clj-refactor nil 't)) (ignore (message (format "Cannot load %s" 'clj-refactor))) (let ((now (current-time))) (message "%s..." #1="Configuring package clj-refactor") (prog1 (progn (condition-case err (progn (setq cljr-auto-sort-ns nil) (setq cljr-favor-prefix-notation nil) (add-hook 'clojure-mode-hook #'...)) ((debug error) (ignore (display-warning ... ... :error)))) t) (let ((elapsed (float-time (time-subtract ... now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" #1# elapsed) (message "%s...done" #1#))))))
  (prog1 (if (not (require 'clj-refactor nil 't)) (ignore (message (format "Cannot load %s" 'clj-refactor))) (let ((now (current-time))) (message "%s..." #1="Configuring package clj-refactor") (prog1 (progn (condition-case err (progn (setq cljr-auto-sort-ns nil) (setq cljr-favor-prefix-notation nil) (add-hook ... ...)) ((debug error) (ignore ...))) t) (let ((elapsed (float-time ...))) (if (> elapsed 0.1) (message #3="%s...done (%.3fs)" #1# . #4=(elapsed)) (message #5="%s...done" #1#)))))) (let ((elapsed (float-time (time-subtract #2=(current-time) now)))) (if (> elapsed 0.1) (message #3# #6="Loading package clj-refactor" . #4#) (message #5# #6#))))
  (let ((now . #1=((current-time)))) (message #2="%s..." #6="Loading package clj-refactor") (prog1 (if (not (require 'clj-refactor nil 't)) (ignore (message (format "Cannot load %s" 'clj-refactor))) (let ((now . #1#)) (message #2# #3="Configuring package clj-refactor") (prog1 (progn (condition-case err (progn ... ... ...) (... ...)) t) (let ((elapsed ...)) (if (> elapsed 0.1) (message #5="%s...done (%.3fs)" #3# . #7=...) (message #8="%s...done" #3#)))))) (let ((elapsed (float-time (time-subtract #4=(current-time) now)))) (if (> elapsed 0.1) (message #5# #6# . #7#) (message #8# #6#)))))
  (progn (use-package-ensure-elpa 'clj-refactor 't 'nil :ensure) (let ((now . #1=((current-time)))) (message #2="%s..." #6="Loading package clj-refactor") (prog1 (if (not (require 'clj-refactor nil 't)) (ignore (message (format "Cannot load %s" 'clj-refactor))) (let ((now . #1#)) (message #2# #3="Configuring package clj-refactor") (prog1 (progn (condition-case err ... ...) t) (let (...) (if ... ... ...))))) (let ((elapsed (float-time (time-subtract #4=... now)))) (if (> elapsed 0.1) (message #5="%s...done (%.3fs)" #6# . #7=(elapsed)) (message #8="%s...done" #6#))))))
  eval((progn (use-package-ensure-elpa 'clj-refactor 't 'nil :ensure) (let ((now . #1=((current-time)))) (message #2="%s..." #6="Loading package clj-refactor") (prog1 (if (not (require 'clj-refactor nil 't)) (ignore (message (format "Cannot load %s" ...))) (let ((now . #1#)) (message #2# #3="Configuring package clj-refactor") (prog1 (progn ... t) (let ... ...)))) (let ((elapsed (float-time ...))) (if (> elapsed 0.1) (message #5="%s...done (%.3fs)" #6# . #7=(elapsed)) (message #8="%s...done" #6#)))))) nil)
  elisp--eval-last-sexp(nil)
```

I install `clj-refactor` from MELPA.
And Emacs version: `26.0.50`
CIDER version `0.15.0-SNAPSHOT`
System: Arch Linux

**Comment by benedekfazekas** [comment] 2017-05-01 05:59
i think this is a duplicate of #369 let me know and reopen if you don't agree

**Closed by benedekfazekas** 2017-05-01 05:59 UTC
