### ISSUE TITLE
Cannot evaluate projects via TRAMP

### ISSUE THREAD

**Issue by weissjeffm** [clojure-emacs/clj-refactor.el#356] opened 2017-01-09 14:11 UTC
## Expected behavior
Can use refactor functions on projects connected to via TRAMP

## Actual behavior
For example, cljr-rename-symbol results in this:

```
To perform this op the project needs to be evaluated.
  Analyzing a large project might take a while: hit C-g to abort.
  (Set cljr-warn-on-eval to nil to analyze the project without warning)
  Do you want to proceed? (y or n) y
Fetching symbol occurrences...
cljr--get-error-value: Error in nrepl-refactor: java.io.FileNotFoundException: /ssh:192.168.66.128:/build/myproject/src/myproject/core.clj (No such file or directory)
 at java.io.FileInputStream.open0 (FileInputStream.java:-2)
    java.io.FileInputStream.open (FileInputStream.java:195)
    java.io.FileInputStream.<init> (FileInputStream.java:138)
    clojure.java.io$fn__9520.invokeStatic (io.clj:229)
    clojure.java.io/fn (io.clj:229)
    clojure.java.io$fn__9433$G__9426__9440.invoke (io.clj:69)
    clojure.java.io$fn__9532.invokeStatic (io.clj:258)
    clojure.java.io/fn (io.clj:254)
    clojure.java.io$fn__9433$G__9426__9440.invoke (io.clj:69)
    clojure.java.io$fn__9494.invokeStatic (io.clj:165)
    clojure.java.io/fn (io.clj:165)
    clojure.java.io$fn__9446$G__9422__9453.invoke (io.clj:69)
    clojure.java.io$reader.invokeStatic (io.clj:102)
    clojure.java.io$reader.doInvoke (io.clj:86)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$slurp.invokeStatic (core.clj:6657)
    clojure.core$slurp.doInvoke (core.clj:6657)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    refactor_nrepl.find.find_symbol$find_local_symbol.invokeStatic (find_symbol.clj:200)
    refactor_nrepl.find.find_symbol$find_local_symbol.invoke (find_symbol.clj:189)
    refactor_nrepl.find.find_symbol$find_symbol.invokeStatic (find_symbol.clj:244)
    refactor_nrepl.find.find_symbol$find_symbol.invoke (find_symbol.clj:235)
    refactor_nrepl.middleware$find_symbol_reply.invokeStatic (middleware.clj:60)
    refactor_nrepl.middleware$find_symbol_reply.invoke (middleware.clj:57)
    refactor_nrepl.middleware$wrap_refactor$fn__57583.invoke (middleware.clj:135)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    cider.nrepl.middleware.inspect$wrap_inspect$fn__41918.invoke (inspect.clj:101)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    clojure.tools.nrepl.middleware.session$add_stdin$fn__37051.invoke (session.clj:238)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    cider.nrepl.middleware.pprint$wrap_pprint$fn__38924.invoke (pprint.clj:108)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    cider.nrepl.middleware.macroexpand$wrap_macroexpand$fn__46917.invoke (macroexpand.clj:226)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    clojure.tools.nrepl.middleware.pr_values$pr_values$fn__36888.invoke (pr_values.clj:22)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    cider.nrepl.middleware.test$wrap_test$fn__47420.invoke (test.clj:309)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    cider.nrepl.middleware.resource$wrap_resource$fn__47281.invoke (resource.clj:27)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    cider.nrepl.middleware.debug$wrap_debug$fn__42214.invoke (debug.clj:648)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    cider.nrepl.middleware.pprint$wrap_pprint_fn$fn__38898.invoke (pprint.clj:50)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    cider.nrepl.middleware.enlighten$wrap_enlighten$fn__42258.invoke (enlighten.clj:86)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    cider.nrepl.middleware.undef$wrap_undef$fn__47800.invoke (undef.clj:22)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    lg_api.core$eval57647$fn__57648$fn__57650.invoke (form-init4261407684939497775.clj:1)
    cider.nrepl.middleware.trace$wrap_trace$fn__47694.invoke (trace.clj:36)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    cider.nrepl.middleware.track_state$wrap_tracker$fn__47773.invoke (track_state.clj:205)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    clojure.tools.nrepl.middleware.session$session$fn__37036.invoke (session.clj:192)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__36701.invoke (middleware.clj:22)
    clojure.tools.nrepl.server$handle_STAR_.invokeStatic (server.clj:19)
    clojure.tools.nrepl.server$handle_STAR_.invoke (server.clj:16)
    clojure.tools.nrepl.server$handle$fn__37109.invoke (server.clj:28)
    clojure.core$binding_conveyor_fn$fn__4676.invoke (core.clj:1938)
    clojure.lang.AFn.call (AFn.java:18)
    java.util.concurrent.FutureTask.run (FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    java.lang.Thread.run (Thread.java:745)
```

# Steps to reproduce the problem
Clone a clojure project on a remote machine. Open the project directory (or any file in the git repo) via tramp, eg, (find-file ssh:192.168.1.1:/workspace/myproject). Then M-x cider-jack-in, then in a clojure file in that project try to do M-x cljr-rename-symbol.
 
### clj-refactor.el version information
2.2.0
### CIDER version information
CIDER 0.15.0snapshot (package: 20161227.21), nREPL 0.2.12

### Leiningen or Boot version
2.6.1
### Emacs version
25.1.1

### Operating system
OS X 10.11.5

**Comment by benedekfazekas** [comment] 2017-01-09 14:46
this is a duplicate of #350 
as said there: happy to look at a PR but I doubt the team will invest much energy in adding this functionality

**Comment by weissjeffm** [comment] 2017-01-09 14:50
Ok thanks, you might want to consider leaving issues open (perhaps tagging them as low priority or "won't fix"). If you close them, the next guy comes along and sees there's no open issue, and submits a new one.

**Comment by benedekfazekas** [comment] 2017-01-09 14:53
+1 as duplicate also shows that this is something ppl want to do with cljr. would be interesting to hear your use case too

**Comment by weissjeffm** [comment] 2017-01-09 15:00
My use case is that I'm developing an application that's distributed as a vm image. My emacs dev environment is on my workstation host, and I run the REPL over tramp on the vm.

**Comment by MalloZup** [comment] 2019-08-05 21:39
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it

**Comment by vemv** [comment] 2022-03-15 04:42
As written [here](https://github.com/clojure-emacs/clj-refactor.el/issues/350#issuecomment-267356702): 

> Feel free to submit a patch if either of you want to maintain that functionality.

> Closing this for now, as the issue will stay open until the project dies otherwise.

**Closed by vemv** 2022-03-15 04:42 UTC
Labels: enhancement, help wanted
