### ISSUE TITLE
Unexpected character (’<’ (code 60))

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/clj-refactor.el#422] opened 2018-06-26 06:32 UTC
## Expected behavior
A list of available libraries comes up after using `cljr-add-project-dependency`.

## Actual behavior
```
Caused by: refactornrepl240SNAPSHOT.com.fasterxml.jackson.core.JsonParseException: Unexpected character (’<’ (code 60)): expected a valid value (number, String, array, object, ’true’, ’false’ or ’null’)
 at [Source: (StringReader); line: 1, column: 2]
 at refactornrepl240SNAPSHOT.com.fasterxml.jackson.core.JsonParser._constructError (JsonParser.java:1798)
    refactornrepl240SNAPSHOT.com.fasterxml.jackson.core.base.ParserMinimalBase._reportError (ParserMinimalBase.java:663)
    refactornrepl240SNAPSHOT.com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar (ParserMinimalBase.java:561)
    refactornrepl240SNAPSHOT.com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue (ReaderBasedJsonParser.java:1892)
    refactornrepl240SNAPSHOT.com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken (ReaderBasedJsonParser.java:747)
    mranderson048.cheshire.v5v8v0.cheshire.parse$parse.invokeStatic (parse.clj:88)
    mranderson048.cheshire.v5v8v0.cheshire.parse$parse.invoke (parse.clj:86)
    mranderson048.cheshire.v5v8v0.cheshire.core$parse_string.invokeStatic (core.clj:206)
    mranderson048.cheshire.v5v8v0.cheshire.core$parse_string.invoke (core.clj:192)
    mranderson048.cheshire.v5v8v0.cheshire.core$parse_string.invokeStatic (core.clj:203)
    mranderson048.cheshire.v5v8v0.cheshire.core$parse_string.invoke (core.clj:192)
    refactor_nrepl.artifacts$get_versions_BANG_.invokeStatic (artifacts.clj:72)
    refactor_nrepl.artifacts$get_versions_BANG_.invoke (artifacts.clj:62)
    refactor_nrepl.artifacts$collate_artifact_and_versions.invokeStatic (artifacts.clj:80)
    refactor_nrepl.artifacts$collate_artifact_and_versions.invoke (artifacts.clj:78)
    clojure.core$partial$fn__5561.invoke (core.clj:2616)
    clojure.core$map$fn__5587.invoke (core.clj:2747)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.RT.seq (RT.java:528)
    clojure.core$seq__5124.invokeStatic (core.clj:137)
    clojure.core$map$fn__5587.invoke (core.clj:2738)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.RT.seq (RT.java:528)
    clojure.core$seq__5124.invokeStatic (core.clj:137)
    clojure.core$dorun.invokeStatic (core.clj:3125)
    clojure.core$dorun.invoke (core.clj:3125)
    refactor_nrepl.artifacts$add_artifacts$fn__16350$fn__16351.invoke (artifacts.clj:89)
    clojure.core$binding_conveyor_fn$fn__5476.invoke (core.clj:2022)
    clojure.lang.AFn.call (AFn.java:18)
    java.util.concurrent.FutureTask.run (FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    java.lang.Thread.run (Thread.java:748)
```

## Steps to reproduce the problem

Provided CIDER and clj-refactor are installed:

- create a new Clojure project with `lein new app test`
- <kbd>C-c M-j</kbd>
- <kbd>C-c RET a p</kbd>

### clj-refactor.el version information

`clj-refactor 2.4.0-SNAPSHOT (package: 20180526.803), refactor-nrepl 2.4.0-SNAPSHOT`

### CIDER version information

```
;; CIDER 0.18.0snapshot (package: 20180624.2344), nREPL 0.2.13
;; Clojure 1.9.0, Java 1.8.0_171
```

### Leiningen or Boot version

`Leiningen 2.8.1 on Java 1.8.0_171 OpenJDK 64-Bit Server VM`

### System details

```
GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2018-06-25

Repository revision: 79c247700f97ca83bf9ab49f21bf45b936b73de6
Configured using:
--host=x86_64-debian-linux-gnu --with-modules

Emacs uptime: 26 minutes, 56 seconds
Colour theme: sanityinc-tomorrow-night
Operating system: Ubuntu 18.04 LTS
Window system: x11
Desktop environment: GNOME Shell 3.28.1
```

**Comment by benedekfazekas** [comment] 2018-06-26 07:53
thanks for flagging. seems to be a duplicate of clojure-emacs/refactor-nrepl#226

**Closed** 2018-06-26 07:54 UTC

**Comment by manuel-uberti** [comment] 2018-06-26 08:00
Sorry didn't catch it.

**Comment by benedekfazekas** [comment] 2018-06-26 08:46
no worries. thanks again for flagging only tracking is easier when there is a single issue
